Gemfile, config/database.yml, test/factories/countries.rb, test/helpers/vcr_helper.rb, test/services/meetup_importilo_test.rb, test/test_helper.rb, test/vcr_cassettes/meetup_success.yml
Sal!
En tiu ĉi aldono mi sendas koncepton por testi eksterajn servojn kiel kun la imortilo.
=> Aldonas provkodo por importilo

app/assets/stylesheets/partials/_page.scss, app/views/layouts/_navbar.haml
Kiel proponita en la grupo "ES teknikaĵoj".
Ankoraŭ necesas ŝanĝi la koloron `rgba(255,255,255,0.5)` al `#fff`, por ke la teksto estu pli facile legebla, sed mi ne certas kiel fari tion...
=> Plibonigi la supran menuon

app/views/events/_informi_pri_problemo.haml, app/views/events/_share_button.haml, app/views/events/by_country.haml, app/views/home/_shortcuts.html.haml, app/views/organizations/show.html.haml
"aria-label" estas por homoj kun vida malkapablo, ĝi prefere diru "fermi" anstataŭ "close".
=> "Close" estu "Fermi"

app/models/event.rb
"Reta urbo" estu simple "Reta", tiel jam estas aliloke en la interfaco.
=> "Reta urbo" estu simple "Reta"

app/views/events/_okazantaj.haml
Kohera kun la aliaj partoj de la interfaco.
=> Ŝanĝis "Enreta" al "Reta"

app/views/home/events.json.jbuilder
=> "Enrete" estu "Reta", akuzativa finaĵo aldonita

.github/FUNDING.yml
Laŭ ĉi tiuj informoj: https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository
=> Subtenbutono ankaŭ en GitHub

app/helpers/home_helper.rb, app/modules/constants.rb, app/views/events/_events_as_map.html.erb, app/views/events/_events_count.html.haml, app/views/events/_okazantaj.haml, test/system/home_test.rb
=> Faru pli klara la indikon de nuntempaj eventoj

config/environments/production.rb, config/environments/staging.rb
Bildo ĉe diskonigita evento #402
=> Adds default_url_options to all environments

.hound.yml, .rubocop.yml, app/controllers/events_controller.rb, app/controllers/users/registrations_controller.rb
=> Ŝanĝi sekurfrazan tekston

app/admin/events.rb, app/assets/stylesheets/colors.scss, app/controllers/events_controller.rb, app/controllers/internacia_controller.rb, app/models/event.rb, app/views/events/_form.haml, db/migrate/20220930123226_add_internacional_calendar_to_events.rb, db/schema.rb
=> Aldonas international_calendar al Events

app/admin/dashboard.rb, app/jobs/create_sample_events_job.rb, app/modules/constants.rb, test/factories/events.rb
=> Button on staging to create sample events

app/javascript/controllers/event_map_controller.js, app/javascript/controllers/map_view_controller.js
... ĉar temas pri (la datumoj malantaŭ) la mapo, kiu estas montrata tie, kie aperas tiu ligilo.
=> aldonas "ĉi" ĉe "tiun mapon"

test/application_system_test_case.rb, test/fixtures/countries.yml, test/system/event_test.rb, test/system/support/authentication_helper.rb
=> E2E test for adding new event

eventaservo.code-workspace, test/system/event_test.rb, test/system/organization_test.rb
=> E2E test for creating new organization

app/components/graphs/new_users_by_month_component.rb, app/jobs/generate_statistics_job.rb, app/views/admin/statistics/index.html.haml, config/schedule.rb, lib/tasks/cron/generate_statistics.rake, spec/components/graphs/new_users_by_month_component_spec.rb, spec/factories/users.rb
Create rake task to generate statistics
Statistics: graph for new users by month
=> Create rake task to generate statistics

app/models/user.rb
=> fix: :bug: Merge users

app/views/layouts/_breadcrumb.html.erb
Fixes EVENTA-SERVO-TW
Fixes EVENTA-SERVO-TZ
=> fix: :bug: breadcrumb links

app/views/events/_uploads.html.erb
=> fix(Event): :bug: delete uploaded file

app/controllers/users/passwords_controller.rb, app/jobs/logs/create_job.rb, app/services/logs/create.rb, app/views/devise/passwords/new.html.erb, spec/jobs/logs/create_job_spec.rb, spec/services/logs/create_spec.rb
=> fix: :bug: Logs password reset request

app/presenters/calendar/add_to_calendar_presenter.rb, app/presenters/calendar/providers/apple.rb, app/presenters/calendar/providers/google.rb, app/presenters/calendar/providers/ics_file.rb, app/presenters/calendar/providers/outlook.rb, app/presenters/calendar/providers/yahoo.rb, app/presenters/event_presenter.rb, app/views/events/_add_to_calendar.html.erb, app/views/events/_options.html.erb, app/views/events/show.html.erb, config/environments/development.rb, config/locales/pages.en.yml, config/locales/pages.eo.yml, config/locales/pages.pt_BR.yml, spec/presenters/calendar/add_to_calendar_presenter_spec.rb, spec/presenters/calendar/providers/apple_spec.rb, spec/presenters/calendar/providers/google_spec.rb, spec/presenters/calendar/providers/ics_file_spec.rb, spec/presenters/calendar/providers/outlook_spec.rb, spec/presenters/calendar/providers/yahoo_spec.rb, spec/presenters/event_presenter_spec.rb
=> feat(Event): :sparkles: Add to Calendar links on event page
